# Generated by Django 3.2.17 on 2023-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='项目名称', max_length=60, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=100, verbose_name='项目负责人')),
                ('tester', models.CharField(blank=True, help_text='测试人员', max_length=200, null=True, verbose_name='测试人员')),
                ('programmer', models.CharField(blank=True, help_text='开发人员', max_length=200, null=True, verbose_name='开发人员')),
                ('publish_app', models.CharField(help_text='发布应用', max_length=100, verbose_name='发布应用')),
                ('desc', models.TextField(blank=True, default='暂无简介', help_text='项目简介', null=True, verbose_name='项目简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'tb_projects',
            },
        ),
    ]
